### ISSUE TITLE
the config of "Remove_Backdoor_FIP.py"

### ISSUE THREAD

**Issue by saulchiu** [nazmul-karim170/FIP-Fisher-Backdoor-Removal#2]
Hi, can u share the config (args) when using "Remove_Backdoor_FIP.py" to prune backdoored model? I use the default config (set eta_F to 0.5), but get poor results.

**Comment by nazmul-karim170** [comment]
Please try 0.005 or less.

**Comment by saulchiu** [comment]
> Please try 0.005 or less.

Thank you! It works!
